controller_joint_names: ['', 
                         'left_wheelhub_joint', 
                         'right_wheelhub_joint', 
                         'left_front_universal_joint', 
                         'left_front_universalWheel_joint', 
                         'left_back_universal_joint', 
                         'left_back_universalWheel_joint', 
                         'right_back_universal_joint', 
                         'right_back_universalWheel_joint', 
                         'right_front_universal_joint', 
                         'right_front_universalWheel_joint', 
                         'shoulder_joint', 
                         'bicep_joint', 
                         'forearm_joint', 
                         'spherocal_wrist_1_joint', 
                         'spherical_wrist_2_joint', 
                         'bracelet_joint', ]
