global_costmap:
  global_frame: map
  robot_base_frame: base_footprint
  
  inflation_radius: 1.65     #  1.0  ,  1.5
  cost_scaling_factor: 12.0  # 11.0   , 25.0,  21

  update_frequency: 10.0
  publish_frequency: 10.0
  transform_tolerance: 0.5

  static_map: true
 
