local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  
  inflation_radius: 1.27     # 1.25  , 1.4,   1.37
  cost_scaling_factor: 8.0  # 19.0  , 9.7,   13.9

  update_frequency: 15.0
  publish_frequency: 15.0
  transform_tolerance: 0.2  
 
  rolling_window: true
  width: 3
  height: 3
  resolution: 0.05
  
