# Params reference: http://wiki.ros.org/move_base#Parameters

# global planners:
#   "navfn/NavfnROS"
#   "global_planner/GlobalPlanner"

# local planners:
#   "dwa_local_planner/DWAPlannerROS"
#   "teb_local_planner/TebLocalPlannerROS"
#


base_global_planner: "global_planner/GlobalPlanner"        # plugin_package_name/planner 
base_local_planner: "teb_local_planner/TebLocalPlannerROS" # plugin_package_name/planner

shutdown_costmaps: false
controller_frequency: 15.0
planner_patience: 5.0
controller_patience: 15.0
conservative_reset_dist: 2.0
planner_frequency: 25.0
oscillation_timeout: 10.0
oscillation_distance: 0.3


